name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run pytest in api container
        run: docker-compose exec -T api pytest test/

      - name: Shut down services
        run: docker-compose down
